spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sportplay?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  elasticsearch:
    rest:
      uris: http://127.0.0.1:9200
      username:
      password:
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.czh.model
server:
  port: 8080
pipeline:
  id: logdelimit-pipeline-id
